# 1. Información del Taller
site_name: Mis notas sobre Linux trabajando con Ubuntu
site_description: Notas muy rápidas de cosas que he ido viendo en Linux y que me resultan útiles
site_author: Federico Coca
site_url: https://fgcoca.github.io/Mis-notas-sobre-Linux-Ubuntu/

# 2. Repositorio
repo_name: fgcoca/Mis-notas-sobre-Linux-Ubuntu
repo_url: https://github.com/fgcoca/Mis-notas-sobre-Linux-Ubuntu
edit_uri: ""

# 3. Copyright
copyright: Copyright &copy; 2022 - 2050 Federico Coca

# 4. RRSS
# extra:
#   social:
#     - icon: fontawesome/brands/twitter-square 
#       link: https://twitter.com/fgcoca
#       name: Twitter de Federico Coca
#     - icon: fontawesome/brands/github
#       link: https://github.com/fgcoca
#       name: Github de Federico Coca
#     - icon: fontawesome/brands/instagram
#       link: https://www.instagram.com/cocafederico/?hl=es
#       name: Instagram de Federico Coca
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/clubroboticagra
#       name: Twitter de Club Robótica Granada 

# 5. Navegación
nav:
  - Introducción: index.md
  - Problema al usar MicroBlocks en Ubuntu: problema_uBlocks.md
  - Actualizar Ubuntu 20.04 a Ubuntu 22.04: A20_22.md
  - Problema de funcionamiento de Pyserial: pyse.md
  - Problema con actualización de Snap Store: psnap.md
  - CH340 / CH341:
    - Dispositivos CH340 USB no funcionan en Ubuntu 22.04: ch340.md
    - Como saber si tengo CH34x instalado: ch340_como.md
  - Archivo AppImage no se ejecuta: archimagen.md
  - Configurar Shutter en Ubuntu 22.04: shu.md
  - Peek no graba el cursor del ratón: peek.md
  - Cerrar programas que no responden: close.md
  - Miscelanea:
    - Autor: Miscelanea/about.md 
    - Licencias: Miscelanea/lic.md
    - Webgrafia/Bibliografía: Miscelanea/webgrafia.md
    - Software utilizado: Miscelanea/soft.md

# 6. Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto

# 7. Configuración del tema
theme:
  name: material
  # Color - Fuentes - Lenguaje
  palette:
    primary: light blue
    accent: deep purple 
  font:
    text: Roboto 
    code: Roboto Mono 
  logo: img/favicon.png 
  favicon: img/favicon.png 
  language: es
  extra:
    search:
      language: es, en
  # Página 404
  static_templates:
    - 404.html
  # No incluir los JavaScript de MkDocs
  #include_search_page: false
  #search_index_only: true

# 8. Extensiones
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      # guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# 9. Necesario para la extensión pydownx.arithmatex
extra_javascript:
  # Este fichero es opcional y solo si se quiere sobreescribir la configuracion del plugin
  #- js/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

# 10. Plugins
plugins:
  - search
  - minify:
      minify_html: true
